routes/web.php
<?php

/**
 * Global Routes
 * Routes that are used between both frontend and backend.
 */

// Switch between the included languages
Route::get('lang/{lang}', 'LanguageController@swap');

/* ----------------------------------------------------------------------- */

/*
 * Frontend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    includeRouteFiles(__DIR__.'/Frontend/');
});

/* ----------------------------------------------------------------------- */

/*
 * Backend Routes
 * Namespaces indicate folder structure
 */
Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['admin', 'dashboardGeneral']], function () {
    Route::get('/', 'DashboardController@index');
    includeRouteFiles(__DIR__.'/Backend/');
});

Route::get('test', '\App\Services\Remote\Fitbit\Fitbit@test');
Route::get('get-steps', '\App\Services\Remote\Fitbit\Fitbit@getSteps');
Route::get('get-profile', '\App\Services\Remote\Fitbit\Fitbit@getUserProfile');
Route::get('get-device', '\App\Services\Remote\Fitbit\Fitbit@getDevice');

app/Models/HealthLog/Calorie/CalorieLog.php
<?php

namespace App\Models\HealthLog\Calorie;

use App\Models\HealthLog\HealthLog;
use Illuminate\Database\Eloquent\Model;

class CalorieLog extends Model
{
    protected $table = 'calorie_logs';
    public $timestamps = false;

    public function log() {
    	return $this->morphOne(HealthLog::class, 'loggable');
    }
}

app/Models/HealthLog/Glucose/GlucoseLog.php
<?php

namespace App\Models\HealthLog\Glucose;

use App\Models\HealthLog\HealthLog;
use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\HealthLogLabel;
use App\Models\Access\User\User;

class GlucoseLog extends Model
{
    protected $table = 'glucose_logs';
    protected $with = ['label'];

    public function log() {
        return $this->morphOne(HealthLog::class, 'loggable');
    }

    public function label() {
    	return $this->belongsTo(HealthLogLabel::class, 'health_log_label_id');
    }

    public function scopeBetweenDates($query, $dateFromObj, $dateToObj) {
        return $query->whereHas('log', function($query) use($dateFromObj, $dateToObj) {
            $query->whereBetween('log_ts', [$dateFromObj, $dateToObj]);
        });
    }

    public function getDescGoalDiff($logParent, $healthGoal) {
        // get descriptive goal difference (low/normal/high) with deviation percentage
        $minBefore = $healthGoal->min_bg_before_meal;
        $maxBefore = $healthGoal->max_bg_before_meal;
        $maxAfter = $healthGoal->max_bg_after_meal;
        $mealRel = $this->label->meal_rel;
        $value = $logParent->value;
        $maxValue = $maxAfter;
        $minValue = $minBefore;
        if ($mealRel == 1 || $mealRel == 2) {
            if ($mealRel == 1) {
                $maxValue = $maxBefore;
                $minValue = $minBefore;
            }
            if ($mealRel == 2) {
                $maxValue = $maxAfter;
                $minValue = $minBefore;
            }
        }
        else {
        }

        $desc = 'normal';
        $deviationPerc = null;
        $log = $logParent;
        if ($value < $minValue) {
            $desc = 'low';
            $deviationPerc = round(($value/$minBefore)*100, 1) - 100;
        }
        if ($value > $maxValue) {
            $desc = 'high';
            $deviationPerc = round(($value/$maxAfter)*100, 1) - 100;
        }
        return [
            'log' => $log,
            'desc' => $desc,
            'deviation_percentage' => $deviationPerc
        ];
    }
}

app/Models/HealthLog/HealthLog.php
<?php

namespace App\Models\HealthLog;

use Illuminate\Database\Eloquent\Model;
use App\Models\Access\User\User;
use App\Models\HealthLog\HealthLogType;
use App\Models\GlucometerDevice\GlucometerDevice;

class HealthLog extends Model
{
    protected $table = 'health_logs';
    protected $dates = [
		'log_ts'
	];
    protected $with = [
        'logType', 'loggable'
    ];

    public function loggable() {
        return $this->morphTo();
    }

    public function patient() {
    	return $this->belongsTo(User::class, 'user_id');
    }

    public function logType() {
        return $this->belongsTo(HealthLogType::class, 'log_type');
    }
    
    public function glucometerDevice() {
        return $this->belongsTo(GlucometerDevice::class, 'glucometer_devices_logs');
    }

    public function scopeGlucoseLogs($q) {
        return $q->whereHas('logType', function($q) { $q->where('type', 'glucose'); });
    }

    public function scopeInsulinLogs($q) {
        return $q->whereHas('logType', function($q) { $q->where('type', 'insulin'); });
    }

    public function scopeStepLogs($q) {
        return $q->whereHas('logType', function($q) { $q->where('type', 'step'); });
    }

    public function scopeCalorieLogs($q) {
        return $q->whereHas('logType', function($q) { $q->where('type', 'calorie'); });
    }

    public function scopePhysicalActivityLogs($q) {
        return $q->whereHas('logType', function($q) { $q->where('type', 'physical_activity'); });
    }

    public function scopeSleepLogs($q) {
        return $q->whereHas('logType', function($q) { $q->where('type', 'sleep'); });
    }

    public function getInsertTypeStringAttribute() {
        if ($this->insert_type == 1) return 'uređaj';
        return 'korisnik';
    }

    public function getHmsFromSecAttribute() {
        // value in ms
        $seconds = $this->value/1000;
        $H = floor($seconds/3600);
        $m = ($seconds/60)%60;
        $s = $seconds%60;
        return sprintf("%02d:%02d:%02d", $H, $m, $s);
    }

    public function getValueAttribute($value) {
        if ($this->log_type == 1) return round($value, 1);
        return round($value, 0);
    }
}

app/Models/HealthLog/HealthLogLabel.php
<?php

namespace App\Models\HealthLog;

use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\Glucose\GlucoseLog;

class HealthLogLabel extends Model
{
    protected $table = 'health_log_labels';

    public function glucoseLogs() {
    	return $this->hasMany(GlucoseLog::class, 'health_log_label_id');
    }
}

app/Models/HealthLog/HealthLogType.php
<?php

namespace App\Models\HealthLog;

use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\HealthLog;

class HealthLogType extends Model
{
	protected $table = "health_log_types";
	
    public function logs() {
    	return $this->hasMany(HealthLog::class, 'log_type');
    }
}

app/Models/HealthLog/Insulin/InsulinLog.php
<?php

namespace App\Models\HealthLog\Insulin;

use App\Models\HealthLog\HealthLog;
use Illuminate\Database\Eloquent\Model;
use App\Models\Access\User\User;
use App\Models\HealthLog\Insulin\InsulinLogType;
use App\Models\HealthLog\HealthLogLabel;

class InsulinLog extends Model
{
    protected $table = 'insulin_logs';
    protected $with = ['insulinType', 'label'];

    public function log() {
        return $this->morphOne(HealthLog::class, 'loggable');
    }

    public function insulinType() {
    	return $this->belongsTo(InsulinLogType::class, 'insulin_type_id');
    }

    public function label() {
    	return $this->belongsTo(HealthLogLabel::class, 'health_log_label_id');
    }
}

app/Models/HealthLog/Insulin/InsulinLogType.php
<?php

namespace App\Models\HealthLog\Insulin;

use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\Insulin\InsulinLog;

class InsulinLogType extends Model
{
    protected $table = 'insulin_log_types';

    public function log() {
    	return $this->hasMany(InsulinLog::class, 'insulin_type_id');
    }
}

app/Models/HealthLog/PhysicalActivity/PhysicalActivityLog.php
<?php

namespace App\Models\HealthLog\PhysicalActivity;

use App\Models\HealthLog\HealthLog;
use Illuminate\Database\Eloquent\Model;

class PhysicalActivityLog extends Model
{
    protected $table = 'physical_activity_logs';
    public $timestamps = false;

    public function log() {
        return $this->morphOne(HealthLog::class, 'loggable');
    }

    public function formattedDurationMinutes() {
    	return round(($this->log->value/1000)/60, 0);
    }

    public function formattedDurationHi() {
    	return gmdate('H:i', $this->log->value/1000);
    }
}

app/Models/HealthLog/Sleep/SleepLog.php
<?php

namespace App\Models\HealthLog\Sleep;

use App\Models\HealthLog\HealthLog;
use Illuminate\Database\Eloquent\Model;

class SleepLog extends Model
{
    protected $table = 'sleep_logs';
    public $timestamps = false;

    public function log() {
        return $this->morphOne(HealthLog::class, 'loggable');
    }
}

app/Models/HealthLog/Step/StepLog.php
<?php

namespace App\Models\HealthLog\Step;

use App\Models\HealthLog\HealthLog;
use Illuminate\Database\Eloquent\Model;

class StepLog extends Model
{
    protected $table = 'step_logs';
    public $timestamps = false;

    public function log() {
        return $this->morphOne(HealthLog::class, 'loggable');
    }
}

app/Models/HealthLog/Weight/WeightLog.php
<?php

namespace App\Models\HealthLog\Weight;

use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\Weight\WeightLogType;
use App\Models\HealthLog\Weight\WeightLogCalc;
use App\Models\Access\User\User;
use App\Models\HealthLog\HealthLog;

class WeightLog extends Model
{
    protected $table = "weight_logs";
    protected $with = ['calculations'];

    public function log() {
        return $this->morphOne(HealthLog::class, 'loggable');
    }

    public function weightLogType() {
    	return $this->belongsTo(WeightLogType::class, 'weight_log_type_id');
    }

    public function calculations() {
    	return $this->hasOne(WeightLogCalc::class, 'weight_log_id');
    }

    public function patient() {
    	return $this->belongsTo(User::class, 'user_id');
    }
}

app/Models/HealthLog/Weight/WeightLogCalc.php
<?php

namespace App\Models\HealthLog\Weight;

use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\Weight\WeightLog;

class WeightLogCalc extends Model
{
    protected $table = 'weight_log_calcs';

    public function log() {
    	return $this->belongsTo(WeightLog::class, 'weight_log_id');
    }

    public function getBmiAttribute($value) {
    	return round($value, 1);
    }

    public function getWhtrAttribute($value) {
    	return round($value, 1);
    }
}

app/Models/HealthLog/Weight/WeightLogType.php
<?php

namespace App\Models\HealthLog\Weight;

use Illuminate\Database\Eloquent\Model;
use App\Models\HealthLog\Weight\WeightLog;

class WeightLogType extends Model
{
    protected $table = 'weight_log_types';

    public function log() {
    	return $this->hasMany(WeightLog::class, 'weight_log_type_id');
    }
}

app/Http/Controllers/Api/HealthLogController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use App\Models\HealthLog\HealthLogLabel;
use App\Models\HealthLog\Insulin\InsulinLogType;

use App\Repositories\Backend\HealthGoal\HealthGoalRepository;
use App\Repositories\Backend\HealthLog\HealthLogRepository;

class HealthLogController extends Controller
{
    public function __construct(HealthGoalRepository $healthGoalRepo, HealthLogRepository $healthLogRepo) {
        $this->now = Carbon::instance(config('application.time.now'));
        $this->healthGoalRepo = $healthGoalRepo;
        $this->healthLogRepo = $healthLogRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $user, $date = null, $sort = null)
    {
        // currently: fixed amount of logs: weekly
        if ($date == null) {
            $lastLog = $this->healthLogRepo->getLastPatientLog($patient);
            if ($lastLog) $date = $lastLog->log_ts;
            else $date = $this->now;
        }
        $date = Carbon::parse($date);
        $dateFrom = $date->copy()->startOfWeek();
        $dateTo = $date->copy()->endOfWeek();

        $healthGoals = $this->healthGoalRepo->getPatientGoalsBetweenDates($user, $dateFrom, $dateTo);
        $healthLogs = $this->healthLogRepo->getPatientLogsList($user, $healthGoals, $dateFrom, $dateTo, true, $sort);

        return json_encode($healthLogs);
    }

    public function getStats(Request $request, $user, $dateFrom, $dateTo = null)
    {
        // currently: fixed amount of stats: monthly (add possibility to choose a range in the future)
        $dateFrom = Carbon::parse($dateFrom);
        $dateTo = $dateFrom->copy()->addMonth();       

        $healthGoals = $this->healthGoalRepo->getPatientGoalsBetweenDates($user, $dateFrom, $dateTo);
        $stats = $this->healthLogRepo->getSeparatedLogStats($user, $dateFrom, $dateTo);

        $data = [
            'date_from' => $dateFrom->toDateString(),
            'date_to' => $dateTo->toDateString(),
            'stats' => $stats,
            'health_goals' => $healthGoals
        ];

        return json_encode($data);
    }

    public function getCreateData() {
        $labels = HealthLogLabel::get();
        $types = InsulinLogType::get();

        $data = [
            'labels' => $labels,
            'insulin_types' => $types
        ];
        return json_encode($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $user)
    {
        $userId = $user->id;
        $healthLogTypeKey = $request->input('log_type_key');
        $logValue = $request->input('value');
        $logTs = $request->input('log_ts');
        $labelId = $request->input('health_log_label_id');
        $insulinTypeId = $request->input('insulin_type_id');
        
        $healthLog = $this->healthLogRepo->storeHealthLog($userId, $healthLogTypeKey, $logValue, $logTs, $labelId, $insulinTypeId);

        return json_encode($healthLog);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/HealthLog/GlucoseLogController.php
<?php

namespace App\Http\Controllers\Backend\HealthLog;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Backend\HealthLog\Glucose\GlucoseLogRepository;
use App\Repositories\Backend\HealthGoal\HealthGoalRepository;
use App\Models\Access\User\User;

class GlucoseLogController extends Controller
{
    private $glucoseLogRepo;

    public function __construct(GlucoseLogRepository $glucoseLogRepo, HealthGoalRepository $healthGoalRepo) {
        $this->glucoseLogRepo = $glucoseLogRepo;
        $this->healthGoalRepo = $healthGoalRepo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function getGlucoseSummary(Request $request, $userId, $dateFrom, $dateTo) {
        if ($request->ajax()) {
            $user = User::find($userId);
            $summary = $this->glucoseLogRepo->getPatientGlucoseSummary($user, $dateFrom, $dateTo);
            return response()->json($summary);
        }
    }

    //public function getLogsList(Request $request, )
}

resources/views/pdf/health-logs/logs.blade.php
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
		<style>
			body {
				font-family: DejaVu Sans, sans-serif;
			}
			table {
				font-size: 10px;
				border-collapse: collapse;
			}
			table th, table td {
				padding: 4px;
				border: 1px solid #333;
				background: #fff;
			}
			.desc-indicator-symbol.desc-green {
				color: #00a65a;
			}
			.desc-indicator-symbol.desc-red {
				color: #dd4b39;
			}
			table .desc-indicator-symbol {
				font-size: 13px;
			}
			.table-cell-inactive {
				background: #e6e6e6;
				border: 1px solid #333;
			}
			h1 {
				font-size: 18px;
				margin-top: 15px;
				margin-bottom: 5px;
			}
			h2 {
				font-size: 15px;
				padding-top: 20px !important;
				margin-bottom: 5px;
			}
			.stats-table {
				margin-top: 0;
				margin-bottom: 20px;
			}
		</style>
	</head>
	<body>
		<h1>Izvještaj za period:<b> {{ \Carbon\Carbon::parse($logs['date_from'])->format(config('application.time.date_formats.default_date')) }} - {{ \Carbon\Carbon::parse($logs['date_to'])->format(config('application.time.date_formats.default_date')) }}</b></h1>
		@include('pdf.health-logs.includes.total-stats-table', [
			'stats' => $logs['stats']
		])
		@foreach($logs['data'] as $dataKey => $dataValue)
			<h2>
				{{ \Carbon\Carbon::parse($dataValue['date'])->formatLocalized(config('application.time.locale_date_formats.default_day_date')) }}
			</h2>
			@include('pdf.health-logs.includes.total-stats-table', [
				'stats' => $dataValue['stats']
			])
            <div>
                <table>
                    <tr>
                        <th></th>
                        <th></th>
                        <th>Unos</th>
                        <th>Iznos</th>
                        <th>Oznaka</th>
                        <th>Vrsta</th>
                        <th>Kalorije</th>
                        <th>Koraci</th>
                        <th>Otkucaji srca</th>
                        <th>Spavanje</th>
                        <th>Buđenje/nemirnost</th>
                    </tr>
                    @foreach($dataValue['logs'] as $logKey => $logValue)
                        @if($logValue->logType->type == 'glucose')
                            <tr>
                                <td>{{ $logValue->insert_type_string }}</td>
                                <td>{{ $logValue->log_ts->format('H:i') }}</td>
                                <td><b>{{ $logValue->logType->type_name }}</b></td>
                                <td>
                                    @include('pdf.health-logs.includes.glucose-log-value-desc', [
                                        'data' => $logValue->loggable->getDescGoalDiff($logValue, $dataValue['health_goal'])
                                    ])
                                </td>
                                <td>{{ $logValue->loggable->label->display_value }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                            </tr>
                        @endif
                        @if($logValue->logType->type == 'insulin')
                            <tr>
                                <td>{{ $logValue->insert_type_string }}</td>
                                <td>{{ $logValue->log_ts->format('H:i') }}</td>
                                <td><b>{{ $logValue->logType->type_name }}</b></td>
                                <td>{{ $logValue->value }} {{ $_base_units['insulin'] }}</td>
                                <td>{{ $logValue->loggable->label->display_value }}</td>
                                <td>{{ $logValue->loggable->insulinType->display_value }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                            </tr>
                        @endif
                        @if($logValue->logType->type == 'physical_activity')
                            <tr>
                                <td>{{ $logValue->insert_type_string }}</td>
                                <td>{{ $logValue->log_ts->format('H:i') }}</td>
                                <td><b>{{ $logValue->logType->type_name }}</b></td>
                                <td>{{ gmdate('H:i:s', $logValue->value/1000) }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td>{{ $logValue->loggable->calories }} {{ $_base_units['calories'] }}</td>
                                <td>{{ $logValue->loggable->steps }}</td>
                                <td>{{ $logValue->loggable->average_heart_rate }} {{ $_base_units['heart_rate'] }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                            </tr>
                        @endif
                        @if($logValue->logType->type == 'step')
                            <tr>
                                <td>{{ $logValue->insert_type_string }}</td>
                                <td>{{ $logValue->log_ts->format('H:i') }}</td>
                                <td><b>{{ $logValue->logType->type_name }}</b></td>
                                <td>{{ $logValue->value }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                            </tr>
                        @endif
                        @if($logValue->logType->type == 'calorie')
                            <tr>
                                <td>{{ $logValue->insert_type_string }}</td>
                                <td>{{ $logValue->log_ts->format('H:i') }}</td>
                                <td><b>{{ $logValue->logType->type_name }}</b></td>
                                <td>{{ $logValue->value }} {{ $_base_units['calories'] }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                            </tr>
                        @endif
                        @if($logValue->logType->type == 'sleep')
                            <tr>
                                <td>{{ $logValue->insert_type_string }}</td>
                                <td>{{ $logValue->log_ts->format('H:i') }}</td>
                                <td><b>{{ $logValue->logType->type_name }}</b></td>
                                <td>{{ gmdate('H:i:s', $logValue->value/1000) }}</td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td class="table-cell-inactive"></td>
                                <td>{{ gmdate('H:i:s', $logValue->loggable->asleep_mins*60) }}</td>
                                <td>
                                    {{ gmdate('H:i:s', $logValue->loggable->awake_mins*60) }} ({{$logValue->loggable->awake_count}}x)
                                    <br>
                                    {{ gmdate('H:i:s', $logValue->loggable->restless_mins*60) }} ({{$logValue->loggable->restless_count}}x)
                                </td>
                            </tr>
                        @endif
                    @endforeach
                </table>
            </div>
		@endforeach
	</body>
</html>